# Generated by Django 3.1.13 on 2023-01-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_kind'),
        ('values', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='parent_report',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
    ]
